import requests
import json

url = 'http://localhost:5001/auth'
token = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImViYzIwNzkzNTQ1NzExODNkNzFjZWJlZDI5YzU1YmVmMjdhZDJjY2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20veWFsbGFub3cxMiIsImF1ZCI6InlhbGxhbm93MTIiLCJhdXRoX3RpbWUiOjE3MTEyNjkzMzAsInVzZXJfaWQiOiJ1U1lsQXZJN2VYVXVod1ZCRGJwNXZVS2tUdWgyIiwic3ViIjoidVNZbEF2STdlWFV1aHdWQkRicDV2VUtrVHVoMiIsImlhdCI6MTcxMTI2OTMzMCwiZXhwIjoxNzExMjcyOTMwLCJlbWFpbCI6InlvdXNzZWYubWFtb3VuMDNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInlvdXNzZWYubWFtb3VuMDNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.jwqrOZAEpz_unFYwtVx-9LgpUJdNu6W1wTj4R6BVzqkkMAF6Nox_L2RouIVRGrkUCy5RWv-7eWPG-3x6eW9RAtC4iHjSvaBSPlj3JKprTb_re3TBUIHmZ0MJz6HZFQjgK4QvpWSzTgaPapC8ovApHNP2HDgEbSzR9zFFVm-70AC2sgTZ9eaNMZznDDm-3H4Kl5aQ63OYnuOKD-0THhcfNxuq5wDOkmcvkcwNfuzIal8KQQlOpVfaosltP9gdqnbqhAOWQfpYWiwtTi-nAm2RdTOeMFD_IwjYQu49Yf8ObAXdXv2wTIT2U8pxUIbS0HsYT7UiP2xpprc3J3xmPXjvgQ"
data = {'id_token': token}
response = requests.post(url, json=data)

print(response.json())