apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: events-service
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CLOUD_GCP_PROJECT_ID
          value: "yallanow-413400"
        - name: SPRING_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SPRING_DATABASE_NAME
        - name: SPRING_INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SPRING_INSTANCE_CONNECTION_NAME
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SPRING_DATASOURCE_PASSWORD
