---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  labels:
    app: my-app
    service: events-service
spec:
  selector:
    matchLabels:
      app: my-app
      service: events-service
  template:
    metadata:
      labels:
        app: my-app
        service: events-service
    spec:
      containers:
        - name: events-service
          image: events-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-service
  labels:
    app: my-app
    service: groups-service
spec:
  selector:
    matchLabels:
      app: my-app
      service: groups-service
  template:
    metadata:
      labels:
        app: my-app
        service: groups-service
    spec:
      containers:
        - name: groups-service
          image: groups-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-service
  labels:
    app: my-app
    service: images-service
spec:
  selector:
    matchLabels:
      app: my-app
      service: images-service
  template:
    metadata:
      labels:
        app: my-app
        service: images-service
    spec:
      containers:
        - name: images-service
          image: images-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  labels:
    app: my-app
    service: feed-service
spec:
  selector:
    matchLabels:
      app: my-app
      service: feed-service
  template:
    metadata:
      labels:
        app: my-app
        service: feed-service
    spec:
      containers:
        - name: feed-service
          image: feed-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RECOMBEE_DATABASE_ID
              valueFrom:
                secretKeyRef:
                  name: recombee-credentials
                  key: RECOMBEE_DATABASE_ID
            - name: RECOMBEE_REGION
              valueFrom:
                secretKeyRef:
                  name: recombee-credentials
                  key: RECOMBEE_REGION
            - name: RECOMBEE_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: recombee-credentials
                  key: RECOMBEE_SECRET_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: my-app
    service: analytics-service
spec:
  selector:
    matchLabels:
      app: my-app
      service: analytics-service
  template:
    metadata:
      labels:
        app: my-app
        service: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: analytics-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RECOMBEE_DATABASE_ID
              valueFrom:
                secretKeyRef:
                  name: recombee-credentials
                  key: RECOMBEE_DATABASE_ID
            - name: RECOMBEE_REGION
              valueFrom:
                secretKeyRef:
                  name: recombee-credentials
                  key: RECOMBEE_REGION
            - name: RECOMBEE_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: recombee-credentials
                  key: RECOMBEE_SECRET_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: my-app
    service: auth-service
spec:
  selector:
    matchLabels:
      app: my-app
      service: auth-service
  template:
    metadata:
      labels:
        app: my-app
        service: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-load-balancer
  template:
    metadata:
      labels:
        app: nginx-load-balancer
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
